Traceback (most recent call last):
  File "/home/richard/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/richard/.local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/richard/.local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/richard/.local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/richard/anaconda3/envs/fina-4380/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/richard/.local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/richard/.local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/richard/.local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
spy['log Return'].plot(kind='hist', bins=100, density=True, label='Observed')
xs = np.linspace(spy['log Return'].min(), spy['log Return'].max(), 100)
ys = scs.norm.pdf(x=xs, loc=spy['log Return'].mean(), scale=spy['log Return'].std())
plt.plot(xs, ys, label='Normal')
plt.title('Distribution of SPY Daily Log Returns')
plt.xlabel('SPY Daily Log Returns')
plt.ylabel('Density')
plt.legend()
# plt.semilogy()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [10][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m spy[[38;5;124m'[39m[38;5;124mlog Return[39m[38;5;124m'[39m][38;5;241m.[39mplot(kind[38;5;241m=[39m[38;5;124m'[39m[38;5;124mhist[39m[38;5;124m'[39m, bins[38;5;241m=[39m[38;5;241m100[39m, density[38;5;241m=[39m[38;5;28;01mTrue[39;00m, label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mObserved[39m[38;5;124m'[39m)
[1;32m      2[0m xs [38;5;241m=[39m np[38;5;241m.[39mlinspace(spy[[38;5;124m'[39m[38;5;124mlog Return[39m[38;5;124m'[39m][38;5;241m.[39mmin(), spy[[38;5;124m'[39m[38;5;124mlog Return[39m[38;5;124m'[39m][38;5;241m.[39mmax(), [38;5;241m100[39m)
[0;32m----> 3[0m ys [38;5;241m=[39m [43mscs[49m[38;5;241m.[39mnorm[38;5;241m.[39mpdf(x[38;5;241m=[39mxs, loc[38;5;241m=[39mspy[[38;5;124m'[39m[38;5;124mlog Return[39m[38;5;124m'[39m][38;5;241m.[39mmean(), scale[38;5;241m=[39mspy[[38;5;124m'[39m[38;5;124mlog Return[39m[38;5;124m'[39m][38;5;241m.[39mstd())
[1;32m      4[0m plt[38;5;241m.[39mplot(xs, ys, label[38;5;241m=[39m[38;5;124m'[39m[38;5;124mNormal[39m[38;5;124m'[39m)
[1;32m      5[0m plt[38;5;241m.[39mtitle([38;5;124m'[39m[38;5;124mDistribution of SPY Daily Log Returns[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'scs' is not defined
NameError: name 'scs' is not defined

