Traceback (most recent call last):
  File "C:\Users\r.herron\Miniconda3\envs\fina-4380\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\r.herron\Miniconda3\envs\fina-4380\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\r.herron\Miniconda3\envs\fina-4380\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\r.herron\Miniconda3\envs\fina-4380\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\r.herron\Miniconda3\envs\fina-4380\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\r.herron\Miniconda3\envs\fina-4380\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\r.herron\Miniconda3\envs\fina-4380\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\r.herron\Miniconda3\envs\fina-4380\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
returns.loc['2005':'2021'].mean().mul(252)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\core\indexes\base.py:3800[0m, in [0;36mIndex.get_loc[1;34m(self, key, method, tolerance)[0m
[0;32m   3799[0m [38;5;28;01mtry[39;00m:
[1;32m-> 3800[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mcasted_key[49m[43m)[49m
[0;32m   3801[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\_libs\index.pyx:138[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[1;34m()[0m

File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\_libs\index.pyx:165[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[1;34m()[0m

File [1;32mpandas\_libs\hashtable_class_helper.pxi:5745[0m, in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[1;34m()[0m

File [1;32mpandas\_libs\hashtable_class_helper.pxi:5753[0m, in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[1;34m()[0m

[1;31mKeyError[0m: '2005'

The above exception was the direct cause of the following exception:

[1;31mKeyError[0m                                  Traceback (most recent call last)
Cell [1;32mIn [151], line 1[0m
[1;32m----> 1[0m returns[38;5;241m.[39mloc[[38;5;124m'[39m[38;5;124m2005[39m[38;5;124m'[39m:[38;5;124m'[39m[38;5;124m2021[39m[38;5;124m'[39m][38;5;241m.[39mmean()[38;5;241m.[39mmul([38;5;241m252[39m)

File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\core\indexing.py:1074[0m, in [0;36m_LocationIndexer.__getitem__[1;34m(self, key)[0m
[0;32m   1071[0m axis [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39maxis [38;5;129;01mor[39;00m [38;5;241m0[39m
[0;32m   1073[0m maybe_callable [38;5;241m=[39m com[38;5;241m.[39mapply_if_callable(key, [38;5;28mself[39m[38;5;241m.[39mobj)
[1;32m-> 1074[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_getitem_axis[49m[43m([49m[43mmaybe_callable[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m

File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\core\indexing.py:1291[0m, in [0;36m_LocIndexer._getitem_axis[1;34m(self, key, axis)[0m
[0;32m   1289[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(key, [38;5;28mslice[39m):
[0;32m   1290[0m     [38;5;28mself[39m[38;5;241m.[39m_validate_key(key, axis)
[1;32m-> 1291[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_slice_axis[49m[43m([49m[43mkey[49m[43m,[49m[43m [49m[43maxis[49m[38;5;241;43m=[39;49m[43maxis[49m[43m)[49m
[0;32m   1292[0m [38;5;28;01melif[39;00m com[38;5;241m.[39mis_bool_indexer(key):
[0;32m   1293[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_getbool_axis(key, axis[38;5;241m=[39maxis)

File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\core\indexing.py:1325[0m, in [0;36m_LocIndexer._get_slice_axis[1;34m(self, slice_obj, axis)[0m
[0;32m   1322[0m     [38;5;28;01mreturn[39;00m obj[38;5;241m.[39mcopy(deep[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[0;32m   1324[0m labels [38;5;241m=[39m obj[38;5;241m.[39m_get_axis(axis)
[1;32m-> 1325[0m indexer [38;5;241m=[39m [43mlabels[49m[38;5;241;43m.[39;49m[43mslice_indexer[49m[43m([49m[43mslice_obj[49m[38;5;241;43m.[39;49m[43mstart[49m[43m,[49m[43m [49m[43mslice_obj[49m[38;5;241;43m.[39;49m[43mstop[49m[43m,[49m[43m [49m[43mslice_obj[49m[38;5;241;43m.[39;49m[43mstep[49m[43m)[49m
[0;32m   1327[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(indexer, [38;5;28mslice[39m):
[0;32m   1328[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mobj[38;5;241m.[39m_slice(indexer, axis[38;5;241m=[39maxis)

File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\core\indexes\base.py:6597[0m, in [0;36mIndex.slice_indexer[1;34m(self, start, end, step, kind)[0m
[0;32m   6554[0m [38;5;124;03m"""[39;00m
[0;32m   6555[0m [38;5;124;03mCompute the slice indexer for input labels and step.[39;00m
[0;32m   6556[0m 
[1;32m   (...)[0m
[0;32m   6593[0m [38;5;124;03mslice(1, 3, None)[39;00m
[0;32m   6594[0m [38;5;124;03m"""[39;00m
[0;32m   6595[0m [38;5;28mself[39m[38;5;241m.[39m_deprecated_arg(kind, [38;5;124m"[39m[38;5;124mkind[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mslice_indexer[39m[38;5;124m"[39m)
[1;32m-> 6597[0m start_slice, end_slice [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mslice_locs[49m[43m([49m[43mstart[49m[43m,[49m[43m [49m[43mend[49m[43m,[49m[43m [49m[43mstep[49m[38;5;241;43m=[39;49m[43mstep[49m[43m)[49m
[0;32m   6599[0m [38;5;66;03m# return a slice[39;00m
[0;32m   6600[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m is_scalar(start_slice):

File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\core\indexes\base.py:6805[0m, in [0;36mIndex.slice_locs[1;34m(self, start, end, step, kind)[0m
[0;32m   6803[0m start_slice [38;5;241m=[39m [38;5;28;01mNone[39;00m
[0;32m   6804[0m [38;5;28;01mif[39;00m start [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m-> 6805[0m     start_slice [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mget_slice_bound[49m[43m([49m[43mstart[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mleft[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m   6806[0m [38;5;28;01mif[39;00m start_slice [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m   6807[0m     start_slice [38;5;241m=[39m [38;5;241m0[39m

File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\core\indexes\base.py:6724[0m, in [0;36mIndex.get_slice_bound[1;34m(self, label, side, kind)[0m
[0;32m   6721[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_searchsorted_monotonic(label, side)
[0;32m   6722[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mValueError[39;00m:
[0;32m   6723[0m         [38;5;66;03m# raise the original KeyError[39;00m
[1;32m-> 6724[0m         [38;5;28;01mraise[39;00m err
[0;32m   6726[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(slc, np[38;5;241m.[39mndarray):
[0;32m   6727[0m     [38;5;66;03m# get_loc may return a boolean array, which[39;00m
[0;32m   6728[0m     [38;5;66;03m# is OK as long as they are representable by a slice.[39;00m
[0;32m   6729[0m     [38;5;28;01massert[39;00m is_bool_dtype(slc[38;5;241m.[39mdtype)

File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\core\indexes\base.py:6718[0m, in [0;36mIndex.get_slice_bound[1;34m(self, label, side, kind)[0m
[0;32m   6716[0m [38;5;66;03m# we need to look up the label[39;00m
[0;32m   6717[0m [38;5;28;01mtry[39;00m:
[1;32m-> 6718[0m     slc [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mlabel[49m[43m)[49m
[0;32m   6719[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:
[0;32m   6720[0m     [38;5;28;01mtry[39;00m:

File [1;32m~\Miniconda3\envs\fina-4380\lib\site-packages\pandas\core\indexes\base.py:3802[0m, in [0;36mIndex.get_loc[1;34m(self, key, method, tolerance)[0m
[0;32m   3800[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_engine[38;5;241m.[39mget_loc(casted_key)
[0;32m   3801[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:
[1;32m-> 3802[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[0;32m   3803[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[0;32m   3804[0m     [38;5;66;03m# If we have a listlike key, _check_indexing_error will raise[39;00m
[0;32m   3805[0m     [38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise[39;00m
[0;32m   3806[0m     [38;5;66;03m#  the TypeError.[39;00m
[0;32m   3807[0m     [38;5;28mself[39m[38;5;241m.[39m_check_indexing_error(key)

[1;31mKeyError[0m: '2005'
KeyError: '2005'

